# Generated by Django 5.2.4 on 2025-07-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('finding_date', models.DateField(blank=True, null=True)),
                ('finding_url', models.URLField(blank=True, null=True)),
                ('nprm_date', models.DateField(blank=True, null=True)),
                ('nprm_url', models.URLField(blank=True, null=True)),
                ('final_rule_date', models.DateField(blank=True, null=True)),
                ('final_rule_url', models.URLField(blank=True, null=True)),
                ('rescinded_date', models.DateField(blank=True, null=True)),
                ('rescinded_url', models.URLField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
